# Generated by Django 3.2 on 2022-06-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
